target 'IMKXSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for IMKXSDK
  platform :ios, '9.0'
    pod 'YYModel'
    pod 'AFNetworking'
    pod 'IQKeyboardManager'
    pod 'JSONModel'
#    pod 'CDChatList'
    pod 'SocketRocket'
    pod 'FMDB'
end
